name = "lean-numerals"
version = "0.1.0"
defaultTargets = ["lean-numerals"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
maxSynthPendingDepth = 3
pp.proofs = true

[[lean_lib]]
name = "Numerals"

[[lean_exe]]
name = "lean-numerals"
root = "Main"
